# -*- coding: utf-8 -*-
"""PFAF metinlerindeki standart terimlerin Turkce karsiliklari.

Bu sozlukler sadece CEVIRI yapar; yeni bilgi uretmez. Boylece her Turkce
alan, kaynaktaki ingilizce ifadeye geri izlenebilir.
"""

MONTHS = {
    "january": "Ocak",
    "february": "Şubat",
    "march": "Mart",
    "april": "Nisan",
    "may": "Mayıs",
    "june": "Haziran",
    "july": "Temmuz",
    "august": "Ağustos",
    "september": "Eylül",
    "october": "Ekim",
    "november": "Kasım",
    "december": "Aralık",
}

# PFAF "Suitable for:" toprak ifadeleri
SOIL_TEXTURE = {
    "light (sandy)": "hafif (kumlu)",
    "medium (loamy)": "orta (tınlı)",
    "heavy (clay)": "ağır (killi)",
    "heavy clay": "ağır killi",
}

SOIL_PH = {
    "very acid": "çok asidik",
    "mildly acid": "hafif asidik",
    "acid": "asidik",
    "neutral": "nötr",
    "basic (mildly alkaline)": "bazik (hafif alkali)",
    "basic (midly alkaline)": "bazik (hafif alkali)",
    "very alkaline": "çok alkali",
    "alkaline": "alkali",
}

# Isik ihtiyaci: PFAF cumle kaliplari -> Turkce
LIGHT_RULES = [
    ("cannot grow in the shade", "Gölgede yetişemez; tam güneş ister."),
    ("can grow in full shade (deep woodland)", "Tam gölgede (yoğun orman altı) yetişebilir."),
    ("can grow in full shade", "Tam gölgede yetişebilir."),
    ("can grow in semi-shade (light woodland)", "Yarı gölgede (açık orman altı) yetişebilir."),
    ("can grow in semi-shade", "Yarı gölgede yetişebilir."),
    ("no shade", "Gölgesiz, tam güneşli konum ister."),
    ("semi-shade", "Yarı gölge tolere eder."),
]

# Su/nem ihtiyaci
MOISTURE_RULES = [
    ("cannot tolerate drought", "Kuraklığa dayanamaz; toprağın nemli kalması gerekir."),
    ("can tolerate drought", "Yerleştikten sonra kuraklığa dayanabilir."),
    ("prefers dry or moist soil", "Kuru veya nemli toprağı tercih eder."),
    ("prefers moist soil", "Nemli toprağı tercih eder."),
    ("prefers dry soil", "Kuru toprağı tercih eder."),
    ("prefers wet soil", "Islak toprağı tercih eder."),
    ("can grow in water", "Su içinde yetişebilir."),
    ("tolerate maritime exposure", "Deniz etkisine (tuzlu rüzgâr) dayanıklıdır."),
]

# PFAF bitkisel etki (herbal action) terimleri
ACTIONS = {
    "abortifacient": "düşük yapıcı (abortifasyan)",
    "acrid": "keskin/yakıcı",
    "alterative": "genel düzenleyici (alteratif)",
    "analgesic": "ağrı kesici",
    "anaphrodisiac": "cinsel isteği azaltıcı",
    "anodyne": "ağrı dindirici",
    "antacid": "mide asidini azaltıcı",
    "anthelmintic": "bağırsak paraziti giderici",
    "antibacterial": "antibakteriyel",
    "antibiotic": "antibiyotik etkili",
    "anticholesterolemic": "kolesterol düşürücü",
    "anticoagulant": "kan pıhtılaşmasını azaltıcı",
    "antidandruff": "kepek giderici",
    "antidiarrhoeal": "ishal giderici",
    "antiemetic": "bulantı/kusma önleyici",
    "antifungal": "mantar önleyici",
    "antihaemorrhoidal": "hemoroide iyi gelen",
    "antihydrotic": "terlemeyi azaltıcı",
    "anti-inflammatory": "iltihap giderici",
    "antiinflammatory": "iltihap giderici",
    "antiperiodic": "nöbet/atak önleyici",
    "antiphlogistic": "iltihap giderici",
    "antipruritic": "kaşıntı giderici",
    "antirheumatic": "romatizmaya iyi gelen",
    "antiscorbutic": "iskorbüt önleyici (C vitamini)",
    "antiseptic": "antiseptik",
    "antispasmodic": "kas spazmı çözücü",
    "antitussive": "öksürük kesici",
    "antiviral": "antiviral",
    "aperient": "hafif müshil",
    "aphrodisiac": "cinsel istek artırıcı",
    "appetizer": "iştah açıcı",
    "aromatherapy": "aromaterapi",
    "aromatic": "aromatik",
    "astringent": "büzücü (astrenjan)",
    "bach": "Bach çiçek özü",
    "balsamic": "balzamik",
    "bitter": "acı tonik",
    "cardiac": "kalp üzerine etkili",
    "cardiotonic": "kalp güçlendirici",
    "carminative": "gaz giderici",
    "cholagogue": "safra söktürücü",
    "contraceptive": "gebelik önleyici",
    "demulcent": "yumuşatıcı (mukoza koruyucu)",
    "deobstruent": "tıkanıklık açıcı",
    "deodorant": "koku giderici",
    "depurative": "kan temizleyici",
    "detergent": "temizleyici",
    "diaphoretic": "terletici",
    "digestive": "sindirim düzenleyici",
    "diuretic": "idrar söktürücü",
    "emetic": "kusturucu",
    "emmenagogue": "adet söktürücü",
    "emollient": "cilt yumuşatıcı",
    "expectorant": "balgam söktürücü",
    "febrifuge": "ateş düşürücü",
    "galactofuge": "süt salgısını azaltıcı",
    "galactogogue": "süt artırıcı",
    "haemostatic": "kanama durdurucu",
    "hallucinogenic": "halüsinojen",
    "hepatic": "karaciğere etkili",
    "homeopathy": "homeopati",
    "hypnotic": "uyku getirici",
    "hypoglycaemic": "kan şekeri düşürücü",
    "hypotensive": "tansiyon düşürücü",
    "laxative": "müshil",
    "lenitive": "yatıştırıcı",
    "lithontripic": "taş dökücü",
    "narcotic": "narkotik",
    "nervine": "sinir sistemini yatıştırıcı",
    "odontalgic": "diş ağrısı giderici",
    "ophthalmic": "göz rahatsızlıklarında kullanılan",
    "oxytocic": "rahim kasılmasını uyarıcı",
    "parasiticide": "parazit öldürücü",
    "pectoral": "göğüs/solunum yumuşatıcı",
    "poultice": "lapa (harici uygulama)",
    "purgative": "kuvvetli müshil",
    "refrigerant": "serinletici",
    "resolvent": "eritici/çözücü",
    "rubefacient": "cildi kızartıcı (dolaşım artırıcı)",
    "sedative": "sakinleştirici",
    "sialagogue": "tükürük artırıcı",
    "stimulant": "uyarıcı",
    "stomachic": "mideyi güçlendirici",
    "styptic": "kanama kesici (harici)",
    "sudorific": "terletici",
    "tonic": "genel güçlendirici (tonik)",
    "vasodilator": "damar genişletici",
    "vermifuge": "solucan düşürücü",
    "vulnerary": "yara iyileştirici",
    "miscellany": "diğer kullanımlar",
    "vitamin c": "C vitamini kaynağı",
    "potherb": "haşlanarak yenen sebze",
    "salve": "merhem",
    # --- ikinci tur: PFAF metinlerinde tespit edilen ek etki terimleri
    "antianxiety": "kaygı giderici",
    "antipanic": "panik hissini azaltıcı",
    "antiasthmatic": "astım şikayetlerini rahatlatıcı",
    "antidepressant": "ruh halini iyileştirici",
    "anticonvulsant": "nöbet önleyici",
    "antipyretic": "ateş düşürücü",
    "adaptogen": "adaptojen (strese uyumu destekleyici)",
    "antitumor": "tümör karşıtı (araştırma aşamasında)",
    "antineoplastics": "tümör karşıtı (araştırma aşamasında)",
    "cytostatic": "hücre çoğalmasını yavaşlatıcı (araştırma aşamasında)",
    "birthing aid": "doğuma yardımcı",
    "vasoconstrictor": "damar büzücü",
    "antidote": "panzehir",
    "antiseborrheic": "sebum (yağlanma) düzenleyici",
    "irritant": "tahriş edici",
    "disinfectant": "dezenfektan",
    "mouthwash": "gargara olarak",
    "antihalitosis": "ağız kokusu giderici",
    "antipsoriatic": "sedef şikayetlerini rahatlatıcı",
    "antiecchymotic": "morluk giderici",
    "antiarthritic": "eklem iltihabını rahatlatıcı",
    "blood purifier": "kan temizleyici",
    "blood tonic": "kan yapıcı",
    "sternutatory": "hapşırtıcı",
    "uterine tonic": "rahim güçlendirici",
    "oxytoxic": "rahim kasılmasını uyarıcı",
    "antiarrhythmic": "kalp ritmini düzenleyici",
    "anaesthetic": "uyuşturucu (lokal anestezik)",
    "mydriatic": "göz bebeğini büyütücü",
    "antiflatulent": "gaz giderici",
    "nutritive": "besleyici",
    "restorative": "güç verici (onarıcı)",
    "decongestant": "tıkanıklık açıcı",
    "antibilious": "safra şikayetlerini giderici",
    "hydrogogue": "güçlü sıvı atıcı",
    "cathartic": "kuvvetli müshil",
    "antiscrophulatic": "lenf bezi şişliklerinde kullanılan",
    "foot care": "ayak bakımında",
}

# PFAF etiket listesinde gecen HASTALIK/DURUM adlari.
# Bunlar farmakolojik etki degil, geleneksel kullanim alanidir; bu yuzden
# "faydasi" gibi degil, ayri bir baslikta gosterilir.
CONDITIONS = {
    "cancer": "kanser",
    "dysentery": "dizanteri",
    "eczema": "egzama",
    "malaria": "sıtma",
    "epilepsy": "sara (epilepsi)",
    "women's complaints": "kadın sağlığı şikayetleri",
    "womens complaints": "kadın sağlığı şikayetleri",
    "infertility": "kısırlık",
    "kidney": "böbrek rahatsızlıkları",
    "leprosy": "cüzzam",
    "tb": "tüberküloz (verem)",
    "cholera": "kolera",
    "vd": "cinsel yolla bulaşan hastalıklar",
    "warts": "siğil",
    "skin": "cilt rahatsızlıkları",
    "urinary": "idrar yolu rahatsızlıkları",
    "stings": "böcek sokması ve ısırıklar",
}

# Yenilebilir kisim / kullanim terimleri
EDIBLE_PARTS = {
    "leaves": "yaprak",
    "leaf": "yaprak",
    "flowers": "çiçek",
    "flower": "çiçek",
    "root": "kök",
    "roots": "kök",
    "seed": "tohum",
    "seeds": "tohum",
    "fruit": "meyve",
    "stem": "gövde",
    "stems": "gövde",
    "bark": "kabuk",
    "shoots": "sürgün",
    "young shoots": "genç sürgün",
    "sap": "özsu",
    "oil": "yağ",
    "gum": "zamk",
    "pollen": "polen",
    "tuber": "yumru",
    "bulb": "soğan (yumru)",
    "rhizome": "rizom (kök sapı)",
    "inner bark": "iç kabuk",
    "flowers and leaves": "çiçek ve yaprak",
    "unknown part": "belirtilmemiş kısım",
}

EDIBLE_USES = {
    "tea": "çay",
    "condiment": "baharat/çeşni",
    "coffee": "kahve yerine",
    "colouring": "renklendirici",
    "curdling agent": "süt pıhtılaştırıcı",
    "drink": "içecek",
    "egg": "yumurta yerine",
    "gum": "sakız",
    "oil": "yağ",
    "pectin": "pektin",
    "salt": "tuz yerine",
    "sweetener": "tatlandırıcı",
    "stabiliser": "kıvam verici",
    "thickener": "koyulaştırıcı",
    "coffee substitute": "kahve yerine",
    "chewing gum": "çiğneme sakızı",
}

# Cografi bolge / ulke adlari
REGIONS = {
    "europe": "Avrupa",
    "s. europe": "Güney Avrupa",
    "c. europe": "Orta Avrupa",
    "n. europe": "Kuzey Avrupa",
    "w. europe": "Batı Avrupa",
    "e. europe": "Doğu Avrupa",
    "se. europe": "Güneydoğu Avrupa",
    "asia": "Asya",
    "w. asia": "Batı Asya",
    "e. asia": "Doğu Asya",
    "c. asia": "Orta Asya",
    "s. asia": "Güney Asya",
    "n. asia": "Kuzey Asya",
    "se. asia": "Güneydoğu Asya",
    "africa": "Afrika",
    "n. africa": "Kuzey Afrika",
    "s. africa": "Güney Afrika",
    "e. africa": "Doğu Afrika",
    "w. africa": "Batı Afrika",
    "tropical africa": "Tropik Afrika",
    "north america": "Kuzey Amerika",
    "south america": "Güney Amerika",
    "c. america": "Orta Amerika",
    "central america": "Orta Amerika",
    "australia": "Avustralya",
    "new zealand": "Yeni Zelanda",
    "britain": "Britanya",
    "turkey": "Türkiye",
    "greece": "Yunanistan",
    "italy": "İtalya",
    "spain": "İspanya",
    "france": "Fransa",
    "germany": "Almanya",
    "china": "Çin",
    "japan": "Japonya",
    "india": "Hindistan",
    "iran": "İran",
    "iraq": "Irak",
    "syria": "Suriye",
    "lebanon": "Lübnan",
    "israel": "İsrail",
    "egypt": "Mısır",
    "morocco": "Fas",
    "algeria": "Cezayir",
    "russia": "Rusya",
    "siberia": "Sibirya",
    "himalayas": "Himalayalar",
    "mediterranean": "Akdeniz",
    "the mediterranean": "Akdeniz havzası",
    "caucasus": "Kafkasya",
    "korea": "Kore",
    "mexico": "Meksika",
    "brazil": "Brezilya",
    "indonesia": "Endonezya",
    "malaysia": "Malezya",
    "thailand": "Tayland",
    "vietnam": "Vietnam",
    "sri lanka": "Sri Lanka",
    "pakistan": "Pakistan",
    "afghanistan": "Afganistan",
    "nepal": "Nepal",
    "canada": "Kanada",
    "united states": "Amerika Birleşik Devletleri",
    "cyprus": "Kıbrıs",
    "portugal": "Portekiz",
    "netherlands": "Hollanda",
    "belgium": "Belçika",
    "austria": "Avusturya",
    "switzerland": "İsviçre",
    "poland": "Polonya",
    "hungary": "Macaristan",
    "romania": "Romanya",
    "bulgaria": "Bulgaristan",
    "serbia": "Sırbistan",
    "croatia": "Hırvatistan",
    "albania": "Arnavutluk",
    "ukraine": "Ukrayna",
    "sweden": "İsveç",
    "norway": "Norveç",
    "finland": "Finlandiya",
    "denmark": "Danimarka",
    "scandinavia": "İskandinavya",
}

# Bitki formu — gunluk dilde anlasilir karsiliklar
HABIT = {
    "annual": "bir mevsim yaşayan",
    "biennial": "iki yılda ömrünü tamamlayan",
    "perennial": "yıllarca yaşayan",
    "evergreen shrub": "kışın da yeşil kalan çalı",
    "deciduous shrub": "kışın yapraklarını döken çalı",
    "evergreen tree": "kışın da yeşil kalan ağaç",
    "deciduous tree": "kışın yapraklarını döken ağaç",
    "shrub": "çalı",
    "tree": "ağaç",
    "climber": "tırmanıcı",
    "bulb": "soğanlı",
    "fern": "eğrelti otu",
}
