# -*- coding: utf-8 -*-
import json

output = {
    "132": {
        "baslik": "Kırlangıçotu sonrası karaciğer hasarı olguları",
        "sorun": "Avrupa'dan gelen 22 hastada büyük kırlangıçotu (Chelidonium majus) kullanımı sonrası zehirli karaciğer hasarı şüphesi vardı.",
        "yaklasim": "Olgular karaciğere özgü uluslararası nedensellik ölçeğiyle yeniden değerlendirildi.",
        "sonuc": "İki olguda nedensellik çok yüksek olasılıklı, altı olguda olası bulundu; kadınlarda daha sık, ortalama 56 yaş, ortalama 36 günlük kullanım ve sarılık öncesi yaklaşık 30 günlük gecikme bildirildi.",
        "anlatim": "Almanya'dan 22 spontan olgu, karaciğere özgü nedensellik ölçeğiyle yeniden puanlandı. Bulgular, kırlangıçotuna bağlı ayrı bir bitkisel karaciğer hasarı formunu destekliyor. Hasar genelde karaciğer hücrelerini etkileyen bir paternle seyrediyor. Veri kalitesi sınırlı olduğu için bazı olgularda nedensellik düşürüldü. Bu metin tıbbi tavsiye değildir.",
        "pubmedId": "21893153",
        "pubmedUrl": "https://pubmed.ncbi.nlm.nih.gov/21893153/",
        "makaleBasligi": "Herbal hepatotoxicity by Greater Celandine (Chelidonium majus): causality assessment of 22 spontaneous reports.",
        "yil": "2011",
        "kaynakAdi": "PubMed"
    },
    "133": {
        "baslik": "Hindibaya bağlı mesleki ve ağızdan alerji",
        "sorun": "Sebze toptancısında hindiba (Cichorium intybus) ile ağız, deri veya solunum yolu teması sonrası alerji belirtileri gelişti; endivye ve marulda da tepki bildirildi.",
        "yaklasim": "SDS-PAGE ve immünoblot ile yaklaşık 48 kDa'lık alerjen tanımlandı; pelin, çim ve huş polenleriyle çapraz reaktivite arandı.",
        "sonuc": "Alerjen bitkinin ışık almayan kısımlarında bulundu; polenlerle çapraz reaksiyon saptanmadı. Hindibaya özgü mesleki alerji olarak ilk olgu sunuldu.",
        "anlatim": "Sebze toptancısında hindiba teması sonrası ani tip alerji belgelendi. Laboratuvar çalışmasında sorumlu protein tanımlandı. Pelin, çim ve huş polenleriyle çapraz duyarlılık bulunmadı; alerjenin kaynağının sebze olduğu düşünüldü. Endivye ve marulda da benzer tepkiler bildirildi. Bu metin tıbbi tavsiye değildir.",
        "pubmedId": "8877160",
        "pubmedUrl": "https://pubmed.ncbi.nlm.nih.gov/8877160/",
        "makaleBasligi": "Inhalative occupational and ingestive immediate-type allergy caused by chicory (Cichorium intybus).",
        "yil": "1996",
        "kaynakAdi": "PubMed"
    },
    "134": {
        "baslik": "Atopik egzamada bitkisel ürünlerle cilt düzelmesi",
        "sorun": "27 yaşındaki kadında atopik egzama (kaşıntılı, tekrarlayan cilt iltihabı), atopi öyküsü ve çoklu alerji vardı; cilt lezyon skoru (EASI) 1,6 idi.",
        "yaklasim": "Üç bitkisel paraparmasötik uygulandı; bunlardan biri büyük dulavratotu (Arctium lappa) kökü içeriyordu.",
        "sonuc": "İki hafta sonra lezyonlar kayboldu ve EASI 0 oldu; altı ay sonra cilt durumu korundu. Dokuzuncu ayda başka bölgede yeni lezyon gelince yine iki günde EASI 0'a indi.",
        "anlatim": "Atopik egzaması olan kadına dulavratotu kökü de dahil üç bitkisel ürün verildi. İki haftada kuru ve kalınlaşmış cilt lezyonları düzeldi. Altı ay boyunca aynı bölgelerde egzama tekrarlamadı. Dokuzuncu ayda başka bölgede lezyon gelince yine kısa sürede düzelme bildirildi. Hasta tedaviden memnun kaldığını belirtti. Bu metin tıbbi tavsiye değildir.",
        "pubmedId": "37043584",
        "pubmedUrl": "https://pubmed.ncbi.nlm.nih.gov/37043584/",
        "makaleBasligi": "Case study of clinical improvement of atopic dermatitis in a patient treated with herbal-based parapharmaceuticals.",
        "yil": "2023",
        "kaynakAdi": "PubMed"
    },
    "136": {
        "baslik": "Solucanotu dahil papatyagiller temas dermatiti",
        "sorun": "Alerjiye yatkın 9 yaşındaki erkek çocukta mevsimsel deri döküntüsü vardı; yazın, özellikle temmuzda kötüleşiyor, ayakkabıyla örtülü ayakları etkilemiyordu.",
        "yaklasim": "Yama testlerinde solucanotu (Tanacetum vulgare), karahindiba, ragweed, adaçayı ve diğer papatyagiller pozitif bulundu; temastan kaçınıldı.",
        "sonuc": "Temastan kaçınınca döküntü düzeldi. Papatyagiller oleoresinlerine bağlı kontak dermatit tanısı kondu.",
        "anlatim": "Alerjik yapısı olan çocukta yaz aylarında kötüleşen deri döküntüsü görüldü. Yama testlerinde solucanotu dahil birçok papatyagil bitkisine duyarlılık saptandı. Döküntü avuç içi ve yüzde belirgindi, ayakkabı altındaki ayak bölgesi etkilenmedi. Temastan kaçınılınca düzelme sağlandı. Bu metin tıbbi tavsiye değildir.",
        "pubmedId": "3827282",
        "pubmedUrl": "https://pubmed.ncbi.nlm.nih.gov/3827282/",
        "makaleBasligi": "Compositae dermatitis in childhood.",
        "yil": "1987",
        "kaynakAdi": "PubMed"
    },
    "137": {
        "baslik": "Ayçiçeği tohumu alerjisi ve pelin çapraz duyarlılığı",
        "sorun": "40 yaşındaki erkek ayçiçeği tohumu yedikten kısa süre sonra nefes darlığı ve kurdeşenle hastaneye yatırıldı; boğaz, ağız ve dilde şişlik vardı.",
        "yaklasim": "Deri çizik testlerinde pelin poleni (Artemisia vulgaris) ve ayçiçeği tohumu güçlü pozitifti; kanda pelin ve yabani ot karışımına karşı IgE yükselmişti.",
        "sonuc": "Pelin polenine alerji ve ayçiçeği tohumu yutması sonrası anafilaktik reaksiyon doğrulandı; çapraz reaktif proteinler saptandı.",
        "anlatim": "Erkek ayçiçeği tohumu yedikten sonra nefes darlığı, kurdeşen ve boğaz şişmesi gelişti. Testler pelin polenine duyarlılığı gösterdi. Ayçiçeği alerjenlerinin pelin alerjenleriyle çapraz reaksiyon verdiği kanıtlandı. Yazarlar reaksiyonun pelin duyarlılığı ve çapraz proteinlerle ilişkili olduğunu belirtti. Bu metin tıbbi tavsiye değildir.",
        "pubmedId": "27222528",
        "pubmedUrl": "https://pubmed.ncbi.nlm.nih.gov/27222528/",
        "makaleBasligi": "Sunflower seed allergy.",
        "yil": "2016",
        "kaynakAdi": "PubMed"
    },
    "138": {
        "baslik": "İlaç dirençli sıtmada tatlı pelin yaprak tableti",
        "sorun": "Altı aylık çalışma döneminde artemisinin kombinasyon tedavisi (ACT) ve damardan artesunata yanıt vermeyen 18 ağır sıtma hastası vardı.",
        "yaklasim": "Hastalara 5 gün boyunca günde iki kez 0,5 g kurutulmuş tatlı pelin (Artemisia annua) yaprak tableti verildi; klinik bulgular ve kan yayması izlendi.",
        "sonuc": "18 hastanın tamamı parazit negatif olup klinik olarak düzelince taburcu edildi; raporda iki pediatrik olgu ayrıntılı anlatıldı.",
        "anlatim": "Standart sıtma ilaçlarına yanıt vermeyen ağır hastalara tatlı pelin yaprak tableti uygulandı. Parazitler mikroskopla saptanamaz hale gelince ve belirtiler geçince hastalar iyileşmiş sayıldı. 18 olgunun tamamında tam iyileşme bildirildi. Bu şefkat amaçlı kullanım serisidir. Bu metin tıbbi tavsiye değildir.",
        "pubmedId": "28732806",
        "pubmedUrl": "https://pubmed.ncbi.nlm.nih.gov/28732806/",
        "makaleBasligi": "Artemisia annua dried leaf tablets treated malaria resistant to ACT and i.v. artesunate: Case reports.",
        "yil": "2017",
        "kaynakAdi": "PubMed"
    },
    "146": {
        "baslik": "Graves hastalığında Çin bitkisel formülü",
        "sorun": "50 yaşındaki kadın ve 56 yaşındaki erkekte Graves tipi hipertiroidi (tiroid bezinin aşırı hormon üretmesi) vardı.",
        "yaklasim": "Jia Wei Xiao Yao San formülü ile kendi kendini iyileştiren ot (Prunella vulgaris), Fritillaria thunbergii ve istiridye kabuğu (Crassostrea gigas) kullanıldı.",
        "sonuc": "Birinci olguda 10 ayda, ikinci olguda 8 ayda tiroid hormonları normale döndü; tedavi sırasında yan etki bildirilmedi ve bir yıldan uzun takipte kontrol sürdü.",
        "anlatim": "Graves hastalığı olan iki hastaya Çin bitkisel formülü verildi. Formülde kendi kendini iyileştiren ot da yer aldı. Aylar süren tedavi sonunda tiroid hormonları normale indi. Her iki hastada da bir yıldan fazla takipte durum kontrol altında kaldı. Tedavi sırasında komplikasyon bildirilmedi. Bu metin tıbbi tavsiye değildir.",
        "pubmedId": "33109498",
        "pubmedUrl": "https://pubmed.ncbi.nlm.nih.gov/33109498/",
        "makaleBasligi": "Successful intervention with Chinese herbal medicine for hyperthyroidism: Two case reports and a literature review.",
        "yil": "2021",
        "kaynakAdi": "PubMed"
    },
    "148": {
        "baslik": "Yüksükotu kaynatmasıyla zehirlenme",
        "sorun": "36 yaşındaki kadın yüksükotu (Digitalis purpurea) kaynatması içtikten sonra bulantı, kusma, karın ağrısı ve yavaş nabızlı kardiyovasküler şok yaşadı.",
        "yaklasim": "Atropin, dimetikon, aljinik asit ve metoklopramid verildi; kan ve idrarda digitalis glikozitleri LC-MS ile ölçüldü.",
        "sonuc": "Beşinci günde belirti kalmadan taburcu edildi; serum glikozit düzeyleri ilk günden itibaren geriledi.",
        "anlatim": "Kadın yüksükotu kaynatması içtikten sonra mide bulantısı ve yavaş kalp atışı gelişti. Kan ve idrarda digitalis glikozitleri saptandı; en yüksek düzeyler ilk günde ölçüldü. Destek tedavisiyle klinik durum düzeldi. Beşinci günde taburcu edildi. Ölümcül olmayan bir zehirlenme olgusu olarak bildirildi. Bu metin tıbbi tavsiye değildir.",
        "pubmedId": "11005196",
        "pubmedUrl": "https://pubmed.ncbi.nlm.nih.gov/11005196/",
        "makaleBasligi": "A non-fatal case of intoxication with foxglove, documented by means of liquid chromatography-electrospray-mass spectrometry.",
        "yil": "2000",
        "kaynakAdi": "PubMed"
    },
    "149": {
        "baslik": "Yenilebilir ot sanılarak zehirli bitki yeme",
        "sorun": "Üç yetişkin yabani pırasa (ramps) sandıkları bitkiyi yedikten sonra tansiyon düşüklüğü, yavaş nabız ve ölçülebilir digoksin benzeri kan düzeyleri gelişti.",
        "yaklasim": "Acil serviste değerlendirildi; bir hastaya digoksin antikoru verildi. Bitki numunesinde Veratrum alkaloidi saptandı.",
        "sonuc": "Üç hasta komplikasyonsuz iyileşti. İnci çiçeği (Convallaria majalis) convallatoksin ile digoksin ölçümünü etkileyebilir.",
        "anlatim": "Üç kişi yenilebilir ot toplarken yanlış bitki yedi. Acil servise tansiyon düşüklüğü ve yavaş nabızla geldiler. Kan testlerinde digoksin benzeri düzeyler ölçüldü. Bitki analizinde toksik alkaloid bulundu. Üç hasta da sorunsuz iyileşti. İnci çiçeği digoksin benzeri maddeler içerir. Bu metin tıbbi tavsiye değildir.",
        "pubmedId": "35691768",
        "pubmedUrl": "https://pubmed.ncbi.nlm.nih.gov/35691768/",
        "makaleBasligi": "Detectable Digoxin Concentrations in 3 Patients with Ramps Misadventure.",
        "yil": "2022",
        "kaynakAdi": "PubMed"
    },
    "150": {
        "baslik": "Astım ve reflüde güzelavrat otu içeren karışım",
        "sorun": "2 yaşındaki erkek çocukta astım ve gastroözofageal reflü (mide asidinin yemek borusuna kaçması) vardı; inhale kortizon, beta agonist ve 6 haftalık mide koruyucu tedaviye yanıt vermedi.",
        "yaklasim": "Pulvis stomachicus cum Belladonna adlı ağızdan karışım verildi; içinde papatya, güzelavrat otu (Atropa belladonna), bizmut ve antimonit bulunuyordu.",
        "sonuc": "Karışım kullanıldıkça belirtiler yavaş yavaş kayboldu; yazarlar mide koruyucu ve bronş genişletici etkileri nedeniyle umut verici buldu.",
        "anlatim": "Astım ve reflüsü olan çocuğa güzelavrat otu içeren antroposofik bir karışım verildi. Standart ilaçlara yanıt alınamamıştı. Karışım sonrası belirtilerde kademeli düzelme gözlendi. Güzelavrat otundaki antikolinerjik maddeler bronş genişlemesine katkı sağlayabilir. Papatya ve bizmutun mide koruyucu etkileri de vardır. Bu metin tıbbi tavsiye değildir.",
        "pubmedId": "26937321",
        "pubmedUrl": "https://pubmed.ncbi.nlm.nih.gov/26937321/",
        "makaleBasligi": "Improvement of Asthma and Gastroesophageal Reflux Disease With Oral Pulvis stomachicus cum Belladonna, a Combination of Matricaria recutita, Atropa belladonna, Bismuth, and Antimonite: A Pediatric Case Report.",
        "yil": "2016",
        "kaynakAdi": "PubMed"
    },
    "151": {
        "baslik": "Banotu dozuna bağlı istenmeyen reaksiyon",
        "sorun": "Genelleşmiş kaygı bozukluğu (Chittodwega) tedavisinde banotu (Hyoscyamus niger) kapsülü alan iki hastada istenmeyen ilaç reaksiyonu gelişti.",
        "yaklasim": "500 mg günlük dozda reaksiyon görüldü; doz 250 mg'a indirildi, biri günde iki kez, biri günde bir kez aldı.",
        "sonuc": "250 mg günde bir kez doz güvenli bulundu; her iki hasta Pitta beden tipindeydi ve banotunun Pitta'yı artırarak reaksiyonu tetiklediği düşünüldü.",
        "anlatim": "Ayurveda tedavisinde banotu kapsülü kullanan iki hastada yan etki görüldü. Aynı dozda birçok başka hastada sorun bildirilmedi. 500 mg doz Pitta tipi iki hastada reaksiyonu tetikledi. Doz 250 mg'a düşürülünce yan etkiler engellendi. Kapha ve Vata tipi hastalarda yan etki gözlenmedi. Bu metin tıbbi tavsiye değildir.",
        "pubmedId": "27011719",
        "pubmedUrl": "https://pubmed.ncbi.nlm.nih.gov/27011719/",
        "makaleBasligi": "Adverse reaction of Parasika Yavani (Hyoscyamus niger Linn): Two case study reports.",
        "yil": "2015",
        "kaynakAdi": "PubMed"
    },
    "152": {
        "baslik": "Moonflower tohumuyla antikolinerjik zehirlenme",
        "sorun": "18 yaşındaki erkek markete getirildiğinde hayal görüyordu ve konuşması dağınıktı; hızlı nabız, genişlemiş göz bebekleri ve kuru, kızarık, sıcak cilt vardı.",
        "yaklasim": "Yoğun bakıma alındı; hastanın moonflower tohumu yediği öğrenildi.",
        "sonuc": "36-48 saatte halüsinasyonlar ve belirtiler düzeldi; dördüncü günde taburcu edildi. Bitkinin Datura inoxia olduğu düşünüldü.",
        "anlatim": "Genç erkek moonflower tohumu yedikten sonra hayal görme ve zihin karışıklığı yaşadı. Hızlı nabız, geniş göz bebekleri ve kuru cilt gibi antikolinerjik bulgular vardı. Yoğun bakımda izlendi. 36-48 saatte belirtiler geçti. Dört gün sonra taburcu edildi. Bu metin tıbbi tavsiye değildir.",
        "pubmedId": "15572604",
        "pubmedUrl": "https://pubmed.ncbi.nlm.nih.gov/15572604/",
        "makaleBasligi": "Antimuscarinic intoxication resulting from the ingestion of moonflower seeds.",
        "yil": "2005",
        "kaynakAdi": "PubMed"
    },
    "153": {
        "baslik": "Kurtboğan zehirlenmesi üç olgu",
        "sorun": "Üç hastada kurtboğan (Aconitum napellus) maruziyeti vardı: 24 yaşındaki kadında bitki yeme sonrası ağır kalp ritim bozukluğu, 2 yaşındaki çocukta deri teması, 34 yaşındaki kadında maydanoz sanarak yeme.",
        "yaklasim": "Ağır olguda canlandırma yapıldı; hafif olguda mide yıkama ve aktif kömür uygulandı.",
        "sonuc": "Ağır olguda ventriküler aritmi (kalpte hızlı ve düzensiz atım) gelişti; spesifik antidot yoktur, destek tedavisi esastır. Hafif olgularda gözlem sırasında belirti gelişmedi.",
        "anlatim": "Üç farklı olguda kurtboğan maruziyeti anlatıldı. Bir kadın bitki yedikten sonra ağır kalp ritim bozukluğu geçirdi ve canlandırıldı. İki yaşındaki çocukta yalnızca ağız çevresinde kızarıklık vardı. Başka bir kadın acı tad nedeniyle hastaneye başvurdu ve mide yıkaması yapıldı. Kurtboğan alkaloidleri ciddi aritmilere yol açabilir. Bu metin tıbbi tavsiye değildir.",
        "pubmedId": "19785799",
        "pubmedUrl": "https://pubmed.ncbi.nlm.nih.gov/19785799/",
        "makaleBasligi": "[Intoxication with Monkshood (Aconitum napellus)].",
        "yil": "2009",
        "kaynakAdi": "PubMed"
    },
    "157": {
        "baslik": "Limonla akraba mantarla göz enfeksiyonu",
        "sorun": "81 yaşındaki çiftçi ve 68 yaşındaki erkekte göz kornea iltihabı (keratit) vardı; etken yeni tanımlanan Diaporthe türleri olarak bildirildi.",
        "yaklasim": "Mantar morfolojisi ve DNA dizileme ile tanımlandı; bir tür limon üzerindeki D. limonicola'ya yakın bulundu. Antifungal duyarlılık testleri yapıldı.",
        "sonuc": "D. oculi ve D. pseudooculi adlı iki yeni tür tanımlandı; tanımlama, ilaç duyarlılığı ve tedavi sonuçları rapor edildi.",
        "anlatim": "İki hastada göz mantar enfeksiyonu görüldü. Etkenler morfoloji ve gen analiziyle yeni Diaporthe türleri olarak tanımlandı. Biri limon üzerindeki yakın türe benziyordu. Antifungal duyarlılık ve tedavi sonuçları bildirildi. Diaporthe türleri nadiren insan hastalığı yapar. Bu metin tıbbi tavsiye değildir.",
        "pubmedId": "30424948",
        "pubmedUrl": "https://pubmed.ncbi.nlm.nih.gov/30424948/",
        "makaleBasligi": "Identification and antifungal sensitivity of two new species of Diaporthe isolated.",
        "yil": "2019",
        "kaynakAdi": "PubMed"
    },
    "158": {
        "baslik": "Sinefrinli takviye sonrası iskemik inme",
        "sorun": "38 yaşındaki erkek bir hafta boyunca sinefrin (acı portakal, Citrus aurantium) ve kafein içeren efedrasız takviye aldıktan sonra bellek kaybı ve dengesiz yürüyüş yaşadı.",
        "yaklasim": "Beyin görüntülemesinde sol talamus ve sol beyincikte subakut enfarktlar saptandı; damar spazmı en olası neden sayıldı.",
        "sonuc": "Neredeyse tam düzelmeyle taburcu edildi. Sinefrinin iskemik inme ile ilişkili olabileceği bildirildi.",
        "anlatim": "Genç erkek bir hafta boyunca sinefrinli diyet takviyesi kullandı. Bellek ve denge sorunları gelişti. Görüntülemede beyinde küçük damar tıkanıklığına bağlı lezyonlar görüldü. Başka nedenler elendi. Taburcu olurken belirtiler büyük ölçüde geçmişti. Sinefrin damarları daraltabilir. Bu metin tıbbi tavsiye değildir.",
        "pubmedId": "15819293",
        "pubmedUrl": "https://pubmed.ncbi.nlm.nih.gov/15819293/",
        "makaleBasligi": "Ischemic stroke associated with use of an ephedra-free dietary supplement containing synephrine.",
        "yil": "2005",
        "kaynakAdi": "PubMed"
    },
    "159": {
        "baslik": "Ardıç altı bitki çeşitliliği karşılaştırması",
        "sorun": "Pannonic kum çayırında yerli ardıç (Juniperus communis) ile istilacı karaçamın (Pinus nigra) alt bitki örtüsüne etkisi incelendi.",
        "yaklasim": "Altı tekil ağaç çevresinde 520 mikrokare ile tür varlığı ölçüldü; bileşimsel çeşitlilik hesaplandı.",
        "sonuc": "Ardıç altında daha karmaşık mikrohabitat ve daha yüksek çeşitlilik bulundu; istilacı çam alt bitki örtüsünü olumsuz etkiledi.",
        "anlatim": "Kum çayırında yerli ardıç ile istilacı karaçamın altındaki bitkiler karşılaştırıldı. Ardıç altında bitki çeşitliliği ve düzeni daha yüksekti. İstilacı çam altında bazı türlerde boşluklar ve kümelenmeler görüldü. Yazarlar istilacı ağaçların uzaklaştırılmasını önerdi. Bu bir ekoloji çalışmasıdır. Bu metin tıbbi tavsiye değildir.",
        "pubmedId": "38429361",
        "pubmedUrl": "https://pubmed.ncbi.nlm.nih.gov/38429361/",
        "makaleBasligi": "A case study on the early stage of Pinus nigra invasion and its impact on species composition and pattern in Pannonic sand grassland.",
        "yil": "2024",
        "kaynakAdi": "PubMed"
    },
    "163": {
        "baslik": "Huş yaprağı metabolit analizi otomasyonu",
        "sorun": "Transgenik izopren salan gümüş huş (Betula pendula) yapraklarında yüksek verimli metabolit analizi gerekiyordu.",
        "yaklasim": "96 kuyucuklu robotik sistemle metabolit özütleme otomatikleştirildi; manuel protokolle karşılaştırıldı.",
        "sonuc": "İzopren salınımı arttıkça flavonoidler, karbonhidratlar, amino asitler ve lipid metabolitleri yükseldi; sükroz izoprenle ters ilişkili bulundu.",
        "anlatim": "Huş yapraklarından metabolit çıkarmak için robotik sistem geliştirildi. Manuel yöntemle karşılaştırılarak tekrarlanabilirlik iyileştirildi. Transgenik huşlarda izopren salınımına bağlı metabolit değişimleri gözlendi. Robotik sistem büyük ölçekli bitki araştırmalarında kullanılabilir. Bu bir laboratuvar yöntem çalışmasıdır. Bu metin tıbbi tavsiye değildir.",
        "pubmedId": "37418159",
        "pubmedUrl": "https://pubmed.ncbi.nlm.nih.gov/37418159/",
        "makaleBasligi": "Automatization of metabolite extraction for high-throughput metabolomics: case study on transgenic isoprene-emitting birch.",
        "yil": "2023",
        "kaynakAdi": "PubMed"
    },
    "164": {
        "baslik": "Korunan alanda kara kavak zehirlenmesi",
        "sorun": "2015'te İsviçre'deki korunan bir koruda yaşlı kara kavak (Populus nigra) ağaçları ani öldü; 2016'da komşu akçaağaç ve ceviz ağaçları da kurumaya başladı.",
        "yaklasim": "Kök boğazında çok sayıda delik bulundu; ağaç halkası, odun anatomisi ve dendrojeokimyasal analizler yapıldı.",
        "sonuc": "Köklerde alüminyum, arsenik, demir, krom, nikel içeren pestisitler veya glifosat benzeri maddeler enjekte edildiği gösterildi; bulgular adli soruşturmada kullanıldı.",
        "anlatim": "Korunan bir alanda ani ölen kara kavaklar incelendi. Köklerde onlarca delik ve kimyasal enjeksiyon izleri saptandı. Bilimsel analizler gizli ağaç zehirlemesini destekledi. Sonuçlar ceza soruşturmasında kullanıldı. Bu bir adli ağaç bilimi çalışmasıdır. Bu metin tıbbi tavsiye değildir.",
        "pubmedId": "32072064",
        "pubmedUrl": "https://pubmed.ncbi.nlm.nih.gov/32072064/",
        "makaleBasligi": "When scientists become detectives: investigating systematic tree poisoning in a protected cove.",
        "yil": "2020",
        "kaynakAdi": "PubMed"
    },
    "165": {
        "baslik": "Migren ve reflüde kaygan karaağaç desteği",
        "sorun": "23 yaşındaki kadında 3 aydır atipik migren vardı; ağır mide-yemek borusu reflüsü nedeniyle beslenmesi değişmişti. İlaç ve kas-iskelet tedavileri yanıtsızdı.",
        "yaklasim": "Diyet ve yaşam tarzı değişikliği, multivitamin, magnezyum oksit ve kaygan karaağaç (Ulmus rubra) önerildi.",
        "sonuc": "Reflü belirtileri düzelince migrenler de iyileşti.",
        "anlatim": "Genç kadında atipik migren ve şiddetli reflü vardı. Önceki tedavilere yanıt alınamamıştı. Diyet düzenlemesi ve kaygan karaağaç dahil destekler verildi. Mide reflüsü düzelince migren şikayetleri de geçti. Tek olgu raporudur. Bu metin tıbbi tavsiye değildir.",
        "pubmedId": "26778934",
        "pubmedUrl": "https://pubmed.ncbi.nlm.nih.gov/26778934/",
        "makaleBasligi": "Dietary and Lifestyle Changes in the Treatment of a 23-Year-Old Female Patient With Migraine.",
        "yil": "2015",
        "kaynakAdi": "PubMed"
    },
    "168": {
        "baslik": "Çin raventi içeren karışımlarla karaciğer hasarı",
        "sorun": "2004'te karaciğer bozukluğu nedeniyle yatırılan 45 kronik hepatit B hastasının yedisinde (%15,6) sorun Çin bitkisel ilaçlarına bağlandı.",
        "yaklasim": "Hepatit B alevlenmesine benzeyen karaciğer bozukluğu paterni görüldü; toksik bileşenler arasında Çin raventi (Rheum palmatum) de yer aldı.",
        "sonuc": "Üç hastada ağır sonuç gelişti: iki ölüm, bir karaciğer nakli; bir hastada siroz hızlandı.",
        "anlatim": "Kronik hepatit B hastalarında Çin bitkisel ilaç kullanımı sonrası karaciğer hasarı tarandı. Yedi olguda bitkilere bağlı bozulma saptandı. Çin raventi şüpheli bileşenler arasında sayıldı. Ölüm ve karaciğer nakli gibi ağır sonuçlar bildirildi. Bir karışımda yüksek toksik bir madde bulundu. Bu metin tıbbi tavsiye değildir.",
        "pubmedId": "17014576",
        "pubmedUrl": "https://pubmed.ncbi.nlm.nih.gov/17014576/",
        "makaleBasligi": "Traditional Chinese medicine causing hepatotoxicity in patients with chronic hepatitis B infection: a 1-year prospective study.",
        "yil": "2006",
        "kaynakAdi": "PubMed"
    },
    "169": {
        "baslik": "Atık sahasında kuzu kulağı ve spontan bitkiler",
        "sorun": "Suzhou'daki kapatılmış inşaat atığı deponisinde ekosistem restorasyonu için spontan bitki türleri incelendi.",
        "yaklasim": "Sahadaki tür bileşimi, çeşitlilik indeksleri ve 26 türün büyüme kapasitesi değerlendirildi.",
        "sonuc": "Kuzu kulağı (Rumex acetosa) yüksek büyüme ve yayılma kapasitesi olan türler arasında sayıldı; deponide çevreye göre daha az tür ve çeşitlilik vardı.",
        "anlatim": "Kapatılmış inşaat atığı sahasındaki kendiliğinden yetişen bitkiler incelendi. Otlar baskın türlerdi. Sahada çevreye kıyasla daha az bitki çeşitliliği bulundu. Güneş seven ve kuraklığa dayanıklı türler yaygındı. Kuzu kulağı restorasyon potansiyeli yüksek türler arasında gösterildi. Bu bir ekoloji çalışmasıdır. Bu metin tıbbi tavsiye değildir.",
        "pubmedId": "38485823",
        "pubmedUrl": "https://pubmed.ncbi.nlm.nih.gov/38485823/",
        "makaleBasligi": "Taking spontaneous plants as a natural strategy for vegetation restoration in construction and demolition waste landfills: a case study in Suzhou, China.",
        "yil": "2024",
        "kaynakAdi": "PubMed"
    },
    "171": {
        "baslik": "Isırgan takviyesi sonrası istemeden süt gelmesi",
        "sorun": "30 yaşındaki obez kadın bir aydır çevresel alerji için 500 mg ısırgan (Urtica dioica) takviyesi alırken yeni başlayan süt gelmesi (galaktore) ile başvurdu.",
        "yaklasim": "Gebelik testi negatif; prolaktin, TSH ve metabolik panel normaldi. Isırgan kesildi, başka ilaç değişikliği yapılmadı.",
        "sonuc": "Bir hafta sonra galaktore tamamen düzeldi.",
        "anlatim": "Kadın alerji için ısırgan takviyesi kullanırken memeden süt gelmesi başladı. Gebelik dışlandı, hormon testleri normaldi. Meme görüntülemelerinde şüpheli bulgu yoktu. Isırgan bırakılınca bir haftada süt gelmesi tamamen geçti. Takviyelerin hormonları etkileyebileceği vurgulandı. Bu metin tıbbi tavsiye değildir.",
        "pubmedId": "34876549",
        "pubmedUrl": "https://pubmed.ncbi.nlm.nih.gov/34876549/",
        "makaleBasligi": "Stinging Nettle (Urtica dioica): An Unusual Case of Galactorrhea.",
        "yil": "2021",
        "kaynakAdi": "PubMed"
    },
    "173": {
        "baslik": "Japonya'da sinirli ot polen alerjisi",
        "sorun": "Hokkaido Üniversitesi kulak burun boğaz polikliniğinde 160 alerjik rinitli hasta incelendi.",
        "yaklasim": "Sinirli ot (Plantago lanceolata) polenine özgü IgE testi, Sapporo polen sayımları ve klinik şikayetler değerlendirildi.",
        "sonuc": "RAST pozitiflik oranı %12,8 bulundu; polen mayıs-eylül arasında dağılıyor, şikayetler haziranda zirve yapıyordu.",
        "anlatim": "Alerjik nezleli 160 hastada sinirli ot polenine duyarlılık araştırıldı. Polen sayımları mayıstan eylüle uzanan bir dönemde yüksekti. IgE testi pozitiflik oranı ragweed ve adaçayıyla benzer düzeydeydi. Hiçbir hasta yalnızca sinirli ota duyarlı değildi. Sonuçlar sinirli otun Japonya'da önemli bir polen kaynağı olabileceğini gösterdi. Bu metin tıbbi tavsiye değildir.",
        "pubmedId": "15885951",
        "pubmedUrl": "https://pubmed.ncbi.nlm.nih.gov/15885951/",
        "makaleBasligi": "Plantago lanceolata (English plantain) pollinosis in Japan.",
        "yil": "2005",
        "kaynakAdi": "PubMed"
    },
    "174": {
        "baslik": "Psyllium laksatifine aşırı duyarlılık",
        "sorun": "40 yaşındaki kadın iki yıl düzenli psyllium (Plantago ovata) laksatif kullandıktan sonra tüm vücutta kaşıntılı döküntü, göğüs-boğaz sıkışması ve dudak şişmesi yaşadı.",
        "yaklasim": "Psyllium kesilince belirtiler geçti; yeniden verilince hemen tekrarladı. Total IgE yüksek, psylliuma özgü IgE pozitifti.",
        "sonuc": "Psyllium aşırı duyarlılığı doğrulandı; alerjenlerin tohum iç kısmındaki proteinlerden geldiği düşünüldü.",
        "anlatim": "Kadın uzun süre psyllium laksatif kullandıktan sonra yaygın döküntü ve nefes darlığı hissi gelişti. Ürün kesilince düzeldi, tekrar alınca belirtiler geri geldi. Kan testlerinde psylliuma karşı IgE saptandı. Alerjenin tohum içindeki proteinlerden kaynaklandığı bildirildi. Bu metin tıbbi tavsiye değildir.",
        "pubmedId": "7998662",
        "pubmedUrl": "https://pubmed.ncbi.nlm.nih.gov/7998662/",
        "makaleBasligi": "Psyllium hypersensitivity.",
        "yil": "1994",
        "kaynakAdi": "PubMed"
    },
    "175": {
        "baslik": "Adet öncesi sendromda keten tohumu yağlı bakım",
        "sorun": "36 yaşındaki kadında 18 yaşından beri adet öncesi sendrom vardı; bel ağrısı, şişkinlik, meme hassasiyeti ve stres yaşıyordu. Semptom skoru 50/60 idi.",
        "yaklasim": "Akupunktur, CoQ10, B kompleksi, magnezyum, keten tohumu yağı (Linum usitatissimum), zerdeçal ve meditasyon uygulandı.",
        "sonuc": "3 ayda 12 seans sonrası skor 18/60'a düştü; 32 hafta daha 20'nin altında kaldı.",
        "anlatim": "Adet öncesi sendromu olan kadına akupunktur ve keten tohumu yağı dahil destekler verildi. Başlangıç semptom skoru 50 idi. Üç ayda skor 18'e indi. Sonraki 32 haftada da 20'nin altında kaldı. Meditasyon stresi azaltmak için önerildi. Tek olgu raporudur. Bu metin tıbbi tavsiye değildir.",
        "pubmedId": "37644997",
        "pubmedUrl": "https://pubmed.ncbi.nlm.nih.gov/37644997/",
        "makaleBasligi": "Management of a Patient With Premenstrual Syndrome Using Acupuncture, Supplements, and Meditation: A Case Report.",
        "yil": "2023",
        "kaynakAdi": "PubMed"
    },
    "176": {
        "baslik": "Delta-8-THC kullanımı sonrası psikoz",
        "sorun": "Üç hasta yalnızca delta-8-tetrahidrokannabinol (Δ8-THC) düzenli kullandıktan sonra psikotik ve paranoid belirtiler geliştirdi; şiddet önceki tablolarını aştı.",
        "yaklasim": "Üçü de üniversite psikiyatri hastanesine yatırıldı.",
        "sonuc": "İki hastada yeni başlangıçlı şiddet ve görsel halüsinasyonlar, birinde banyoda yavruların eridiğine dair sabit sanrılar bildirildi.",
        "anlatim": "Kenevir türevi Δ8-THC kullanan üç kişide ağır psikotik belirtiler gelişti. İki hastada görsel halüsinasyon ve şiddet görüldü. Birinde daha önce psikiyatrik öykü yokken yeni sanrılar başladı. Belirtilerin Δ8-THC kullanımıyla zaman içinde ilişkili olduğu bildirildi. Hekimlerin bu maddeyi sorması önerildi. Bu metin tıbbi tavsiye değildir.",
        "pubmedId": "36890985",
        "pubmedUrl": "https://pubmed.ncbi.nlm.nih.gov/36890985/",
        "makaleBasligi": "Delta-8-THC association with psychosis: A case report with literature review.",
        "yil": "2023",
        "kaynakAdi": "PubMed"
    },
    "177": {
        "baslik": "Kırmızı yonca sonrası kanama bozukluğu",
        "sorun": "28 yaşındaki kadın kırmızı yonca (Trifolium pratense) aldıktan sonra kanama bozukluğu gelişti. Warfarin kullanmıyordu ama kanında warfarin saptandı.",
        "yaklasim": "Kanama bozukluğu değerlendirildi; kırmızı yonca doğal kumarin kaynağı olarak değerlendirildi.",
        "sonuc": "Uluslararası normalize oran (INR, kan sulandırma ölçümü) artışı ve kanama riski ile ilişkilendirildi.",
        "anlatim": "Genç kadın reçetesiz kırmızı yonca aldıktan sonra kanama sorunu yaşadı. Warfarin kullanmadığı halde kanında warfarin saptandı. Yonca doğal kumarin içerebilir ve kan sulandırma ölçümünü etkileyebilir. Hekimlerin bitkisel ürünleri sorması gerektiği vurgulandı. Bu metin tıbbi tavsiye değildir.",
        "pubmedId": "31172083",
        "pubmedUrl": "https://pubmed.ncbi.nlm.nih.gov/31172083/",
        "makaleBasligi": "Coagulation Disorder following Red Clover (Trifolium Pratense) Misuse: a Case Report.",
        "yil": "2018",
        "kaynakAdi": "PubMed"
    },
    "178": {
        "baslik": "Yonca kökü mikoriza sporlarındaki bakteriler",
        "sorun": "Gigaspora margarita mikoriza mantarı sporlarıyla ilişkili bakteri çeşitliliği ve işlevleri bilinmiyordu.",
        "yaklasim": "Yonca (Medicago sativa), sorgum ve mısır konaklarında üretilen sporlardan 43 bakteri izole edildi; 16S analizi yapıldı.",
        "sonuc": "23 cinse ait bakteriler bulundu; bazıları spor çimlenmesini uyardı, %57,5'i fosfor çözdü; saksı deneyinde üç izolat yonca büyümesini artırdı.",
        "anlatim": "Mikoriza mantarı sporları yonca, sorgum ve mısırda çoğaltıldı. Sporlardan 43 bakteri izole edildi. Bacillus ve Streptomyces en sık bulunan cinslerdi. Bazı bakteriler spor çimlenmesini ve fosfor çözünürlüğünü artırdı. Üç izolat yonca büyümesini destekledi. Bu bir tarım mikrobiyolojisi çalışmasıdır. Bu metin tıbbi tavsiye değildir.",
        "pubmedId": "28391471",
        "pubmedUrl": "https://pubmed.ncbi.nlm.nih.gov/28391471/",
        "makaleBasligi": "Population and function analysis of cultivable bacteria associated with spores of arbuscular mycorrhizal fungus Gigaspora margarita.",
        "yil": "2017",
        "kaynakAdi": "PubMed"
    },
    "181": {
        "baslik": "Ağız yanığında zerdeçal jeli ile iyileşme",
        "sorun": "49 yaşındaki kadın Calotropis procera lateksini diş etine sürdükten sonra alt çene ön bölgesinde ağrılı beyaz lezyon geliştirdi.",
        "yaklasim": "Kimyasal yanık tanısı kondu; günde üç kez %2 curcumin (zerdeçal, Curcuma longa) ağız jeli 1-1,5 hafta uygulandı.",
        "sonuc": "7. günde belirtiler belirgin düzeldi; 3 aylık takipte tam iyileşme ve nüks olmadı.",
        "anlatim": "Kadın ağrı gidermek için zehirli bitki lateksini diş etine sürdü. Beyaz, ağrılı bir yanık oluştu. Zerdeçal etken maddeli ağız jeli verildi. Yedinci günde belirtiler büyük ölçüde geçti. Üç ay sonra tam iyileşme doğrulandı. Doğrulanmamış bitkisel tedavilerin riski vurgulandı. Bu metin tıbbi tavsiye değildir.",
        "pubmedId": "40719673",
        "pubmedUrl": "https://pubmed.ncbi.nlm.nih.gov/40719673/",
        "makaleBasligi": "Oral injury from Calotropis procera: A case report on inadvertent gingival damage.",
        "yil": "2026",
        "kaynakAdi": "PubMed"
    },
    "191": {
        "baslik": "Aşırı sinameki çayıyla karaciğer yetmezliği",
        "sorun": "52 yaşındaki kadın 3 yıldan uzun süre her gün 70 g kuru sinameki meyvesinden bir litre çay içtikten sonra akut karaciğer yetmezliği ve böbrek bozukluğu geliştirdi.",
        "yaklasim": "Yoğun bakım destek tedavisi uygulandı; karaciğer nakli görüşüldü. İdrarda geçici yüksek kadmiyum saptandı.",
        "sonuc": "Destek tedaviyle iyileşti; hepatotoksisite sinameki laksatif kötüye kullanımına bağlı olabilir.",
        "anlatim": "Kadın yıllarca çok yüksek doz sinameki çayı içiyordu. Akut karaciğer yetmezliği, bilinç bozukluğu ve böbrek sorunları gelişti. Karaciğer nakli düşünüldü ama destek tedaviyle düzeldi. Yazarlar büyük sinameki dozlarının karaciğer hasarı riski taşıdığını belirtti. Bu metin tıbbi tavsiye değildir.",
        "pubmedId": "15956233",
        "pubmedUrl": "https://pubmed.ncbi.nlm.nih.gov/15956233/",
        "makaleBasligi": "Acute liver failure with renal impairment related to the abuse of senna anthraquinone glycosides.",
        "yil": "2005",
        "kaynakAdi": "PubMed"
    },
    "192": {
        "baslik": "Pazopanib ile kudret narı etkileşiminde pankreatit",
        "sorun": "65 yaşındaki böbrek kanseri hastası 8. yıl pazopanib tedavisindeyken 4 gün kudret narı özütü (günde 100-150 ml) aldıktan sonra karın ağrısı, bulantı ve kusma gelişti.",
        "yaklasim": "Pazopanib kesildi, akut pankreatit tedavisi uygulandı; amilaz 9163 U/L, lipaz 14.206 U/L idi.",
        "sonuc": "Hasta düzelince pazopanib yeniden başlandı; enzimler tekrar yükselmedi. Kudret narı ile pazopanib etkileşimi olası neden sayıldı.",
        "anlatim": "Kanser ilacı kullanan hasta kısa süre kudret narı özütü aldı. Sonrasında çok yüksek pankreas enzimleriyle akut pankreatit gelişti. İlaç kesilip tedavi edildi. Düzelince pazopanib yeniden verildi ve sorun tekrarlamadı. İlaç-bitki etkileşimi olasılığı bildirildi. Bu metin tıbbi tavsiye değildir.",
        "pubmedId": "34569860",
        "pubmedUrl": "https://pubmed.ncbi.nlm.nih.gov/34569860/",
        "makaleBasligi": "Dangerous interaction of bitter melon (Momordica charantia) with pazopanib: A case of acute pancreatitis.",
        "yil": "2022",
        "kaynakAdi": "PubMed"
    },
    "193": {
        "baslik": "Mide kanamasında Ankaferd destek tedavisi",
        "sorun": "Düşük trombosit sayısı ve bozuk pıhtılaşması olan hastada zor üst sindirim sistemi kanaması vardı.",
        "yaklasim": "Endoskopik tedavide Ankaferd Blood Stopper destek olarak kullanıldı; içinde küçük havlıcan (Alpinia officinarum) da bulunur.",
        "sonuc": "Kanamanın endoskopik olarak kontrol altına alındığı bildirildi.",
        "anlatim": "Pıhtılaşma sorunu olan hastada üst mide-bağırsak kanaması görüldü. Endoskopik işlem sırasında Ankaferd adlı bitkisel preparat destek olarak kullanıldı. Preparat kekik, meyan, asma, küçük havlıcan ve ısırgan içerir. Kanamanın başarıyla durdurulduğu bildirildi. Bu metin tıbbi tavsiye değildir.",
        "pubmedId": "20677211",
        "pubmedUrl": "https://pubmed.ncbi.nlm.nih.gov/20677211/",
        "makaleBasligi": "Upper gastrointestinal bleeding in a patient with defective hemostasis successfully treated with ankaferd blood stopper.",
        "yil": "2011",
        "kaynakAdi": "PubMed"
    },
    "194": {
        "baslik": "Ağız kimyasal yanığında curcumin jeli",
        "sorun": "49 yaşındaki kadın Calotropis procera lateksini diş etine uyguladıktan sonra alt sağ diş eti bölgesinde ağrılı beyaz lezyon geliştirdi.",
        "yaklasim": "Kimyasal yanık tanısı kondu; curcumin (Curcuma türlerinden elde edilen polifenol) içeren %2 ağız jeli günde üç kez uygulandı.",
        "sonuc": "7. günde belirtiler belirgin düzeldi; 3 aylık takipte tam iyileşme doğrulandı.",
        "anlatim": "Kadın ağrı gidermek için zehirli bitki lateksini diş etine sürdü. Kimyasal yanık oluştu. Curcumin içeren ağız jeli reçete edildi. Yedinci günde belirtiler büyük ölçüde geçti. Üç ay sonra tam iyileşme ve nüks olmadığı bildirildi. Bu metin tıbbi tavsiye değildir.",
        "pubmedId": "40719673",
        "pubmedUrl": "https://pubmed.ncbi.nlm.nih.gov/40719673/",
        "makaleBasligi": "Oral injury from Calotropis procera: A case report on inadvertent gingival damage.",
        "yil": "2026",
        "kaynakAdi": "PubMed"
    },
    "195": {
        "baslik": "Uzun süre zencefil sonrası idrar yakınmaları",
        "sorun": "43 yaşındaki erkek reçetesiz zencefil (Zingiber officinale) kullandıktan sonra idrar akımında kesilme, idrar yakması (dizüri) ve yan ağrısı yaşadı; şikayetler dört yıl sürdü.",
        "yaklasim": "Zencefil alımı kesildi; başka müdahale yapılmadığı bildirildi.",
        "sonuc": "Kesimden sekiz hafta sonra şikayetlerin gerilediği kaydedildi.",
        "anlatim": "Erkek reçetesiz zencefil kullandıktan sonra idrar yaparken yakınma ve yan ağrısı başladı. Şikayetler yıllarca sürdü. Zencefil bırakılınca sekiz haftada belirtiler azaldı. Açıklanamayan idrar şikayetlerinde bitki kullanım öyküsünün sorulması önerildi. Bu metin tıbbi tavsiye değildir.",
        "pubmedId": "34466433",
        "pubmedUrl": "https://pubmed.ncbi.nlm.nih.gov/34466433/",
        "makaleBasligi": "Chronic Dysuria Following Ginger (Zingiber officinale) Use: A Case Report.",
        "yil": "2018",
        "kaynakAdi": "PubMed"
    },
    "196": {
        "baslik": "Büyük havlıcanla alerjik deri döküntüsü",
        "sorun": "Hastada büyük havlıcan (Alpinia galanga) cilde sürülen bitkisel uygulama sonrası yerel temas dermatiti ve ardından yaygın hedef tahtası benzeri döküntü gelişti.",
        "yaklasim": "Yama testlerinde taze ve kuru büyük havlıcanda alerjen saptandı.",
        "sonuc": "Bitkiye bağlı alerjik kontak dermatit ve yaygın eritema multiforme benzeri reaksiyon belgelendi.",
        "anlatim": "Hasta bitkisel karışımı cilde sürdükten sonra önce yerel, sonra yaygın döküntü geliştirdi. Yama testleri büyük havlıcanda alerjen gösterdi. Havlıcan Güneydoğu Asya mutfağında yaygın bir baharattır. Alerjik reaksiyon hem yerel hem genelleşmiş olarak bildirildi. Bu metin tıbbi tavsiye değildir.",
        "pubmedId": "16487286",
        "pubmedUrl": "https://pubmed.ncbi.nlm.nih.gov/16487286/",
        "makaleBasligi": "Erythema multiforme-like generalized allergic contact dermatitis caused by Alpinia galanga.",
        "yil": "2006",
        "kaynakAdi": "PubMed"
    },
    "198": {
        "baslik": "Sirozlu asitte uzun biberli Ayurveda tedavisi",
        "sorun": "Kriptojenik siroz ve portal hipertansiyona bağlı karın sıvısı (asit) olan hasta Ayurveda kliniğine başvurdu.",
        "yaklasim": "Snehapana ve virecana sonrası Vardhamana pippali rasayana (uzun biber, Piper longum) uygulandı.",
        "sonuc": "Asit ve alt bacak ödemi tamamen çözüldü; bir yıllık takipte asit nüksü bildirilmedi.",
        "anlatim": "Siroz ve karın sıvısı olan hastaya Ayurveda tedavisi uygulandı. Tedavide uzun biber (pippali) yapılandırılmış dozla verildi. Asit ve bacak şişliği tamamen geçti. Bir yıl sonra asit tekrarlamadı. Tek olgu raporudur. Bu metin tıbbi tavsiye değildir.",
        "pubmedId": "27621523",
        "pubmedUrl": "https://pubmed.ncbi.nlm.nih.gov/27621523/",
        "makaleBasligi": "Ayurvedic management of cirrhotic ascites.",
        "yil": "2016",
        "kaynakAdi": "PubMed"
    },
    "199": {
        "baslik": "Parkinson'da kadife fasulye ile dopamin düzensizliği",
        "sorun": "Parkinson hastası reçeteli levodopa/karbidopa ile birlikte kendi kendine kadife fasulye (Mucuna pruriens, levodopa içerir) kullandıktan sonra dopamin düzensizlik sendromu (DDS) gelişti.",
        "yaklasim": "DDS, motor belirtileri kontrol etmek için gerekenden fazla dopamin replasman tedavisi kullanımı olarak tanımlandı.",
        "sonuc": "DDS tanısının ve risk faktörlerinin tanınmasının önemli olduğu vurgulandı; hem reçeteli ilaç hem kadife fasulye kötüye kullanımının izlenmesi gerektiği bildirildi.",
        "anlatim": "Parkinson hastası reçeteli levodopa ile birlikte kendi kendine kadife fasulye takviyesi aldı. Bu durum dopamin düzensizlik sendromu ile ilişkilendirildi. Sendrom, dopamin ilacının gereğinden fazla kullanılmasıyla ortaya çıkar. Kadife fasulye de levodopa içerir. Hekimlerin hastaları hem ilaç hem takviye kullanımı konusunda izlemesi önerildi. Bu metin tıbbi tavsiye değildir.",
        "pubmedId": "41220013",
        "pubmedUrl": "https://pubmed.ncbi.nlm.nih.gov/41220013/",
        "makaleBasligi": "Dopamine Dysregulation Syndrome in Parkinson's Disease.",
        "yil": "2025",
        "kaynakAdi": "PubMed"
    },
    "200": {
        "baslik": "Diz kireçlenmesinde akgünlük içeren Ayurveda",
        "sorun": "63 yaşındaki kadında sol dizde ileri osteoartrit (kireçlenme), kemik çıkıntıları, ağrı ve hareket kısıtlılığı vardı.",
        "yaklasim": "70 gün Sri Lanka geleneksel/Ayurveda tedavisi; ardından akgünlük (Boswellia serrata / Shallaki) kapsül ve Jeewya tabletleri 5 ay sürdürüldü.",
        "sonuc": "70 günde ağrı, hareket ve stabilite skorları iyi, işlev skoru mükemmel düzeye çıktı; takip döneminde skorlar değişmedi.",
        "anlatim": "İleri diz kireçlenmesi olan kadına Ayurveda bakımı uygulandı. Sonrasında akgünlük kapsül ve Jeewya tabletleri verildi. Yetmiş günde ağrı ve hareket skorları belirgin iyileşti. Takip döneminde skorlar korundu. Yaşam kalitesinin arttığı bildirildi. Tek olgu raporudur. Bu metin tıbbi tavsiye değildir.",
        "pubmedId": "26195904",
        "pubmedUrl": "https://pubmed.ncbi.nlm.nih.gov/26195904/",
        "makaleBasligi": "Effect of Sri Lankan traditional medicine and Ayurveda on Sandhigata Vata (osteoarthritis of knee joint).",
        "yil": "2014",
        "kaynakAdi": "PubMed"
    },
    "202": {
        "baslik": "Diyabette kas enfarktüsü ve danshen kullanımı",
        "sorun": "İki diyabetli hastada karın duvarı (olgu 1) ve göğüs kası (olgu 2) kas enfarktüsü (kas damar tıkanıklığı) vardı.",
        "yaklasim": "Yatak istirahati, ağrı kesici, yoğun insülin, heparin, silostazol ve kırmızı adaçayı/danshen (Salvia miltiorrhiza) uygulandı.",
        "sonuc": "Üç haftada şikayetler geriledi; bir olguda karşı tarafta nüks 40 günde düzeldi.",
        "anlatim": "Diyabetli iki hastada kas enfarktüsü tanısı kondu. MRI ve biyopsi ile doğrulandı. Destek tedaviye danshen de eklendi. Üç haftada belirtiler azaldı. Bir hastada karın kasında karşı tarafta tekrarlayan enfarktüs 40 günde düzeldi. Bu metin tıbbi tavsiye değildir.",
        "pubmedId": "16401324",
        "pubmedUrl": "https://pubmed.ncbi.nlm.nih.gov/16401324/",
        "makaleBasligi": "Muscle infarction involving muscles of abdominal and thoracic walls in diabetes.",
        "yil": "2005",
        "kaynakAdi": "PubMed"
    },
    "203": {
        "baslik": "Boğada şeytan pençesi meyvesi sıkışması",
        "sorun": "3 yaşındaki Brahman boğada kızgın ineğe aşım denemesinde penis dışarı çıkamıyordu.",
        "yaklasim": "Preputial boşlukta şeytan pençesi (Harpagophytum procumbens) kuru meyvesi bulundu; elle çıkarıldı, antiseptik ve antibiyotik verildi.",
        "sonuc": "Yaralar iyileşti, penis çıkışı ve aşım yeteneği geri geldi.",
        "anlatim": "Botsvana'da bir boğada penis çıkışı engellenmişti. Muayenede preputial boşlukta şeytan pençesi kuru meyvesi bulundu. Meyve çıkarıldı ve tedavi verildi. Yaralar iyileşince boğa normal aşım yapabildi. İlk veteriner olgu olarak bildirildi. Bu metin tıbbi tavsiye değildir.",
        "pubmedId": "11563723",
        "pubmedUrl": "https://pubmed.ncbi.nlm.nih.gov/11563723/",
        "makaleBasligi": "Devil's claw (Harpagophytum procumbens) in a Brahman's preputial sheath: a case report from Botswana.",
        "yil": "2001",
        "kaynakAdi": "PubMed"
    },
    "204": {
        "baslik": "Katar'da meme kanseri bitki bilgisi taraması",
        "sorun": "Katar'da meme kanseri hastaları arasında bitkisel tamamlayıcı tedavi kullanımı yaygın; geleneksel bilgi kaybolma riski taşıyor.",
        "yaklasim": "Doha'da 13 aktarla etnobotanik anket yapıldı; önerilen bitkiler literatürle karşılaştırıldı.",
        "sonuc": "Udi hindi (Saussurea costus), zencefil ve çörek otu en çok önerilen bitkilerdi; birçok bitkinin meme kanseri hücrelerine karşı sitotoksik etkisi literatürde bildirildi.",
        "anlatim": "Katar'da 13 aktar meme kanseri tedavisinde kullandıkları bitkiler hakkında görüşüldü. On farklı familyadan bitki kaydedildi. Udi hindi en sık önerilen bitkilerden biriydi. Bitkilerin çoğu Hindistan ve İran'dan temin ediliyordu. Literatür taramasında antikanser bileşenler ve hücre ölümü yolları bildirildi. Bu bir etnobotanik çalışmadır. Bu metin tıbbi tavsiye değildir.",
        "pubmedId": "40028611",
        "pubmedUrl": "https://pubmed.ncbi.nlm.nih.gov/40028611/",
        "makaleBasligi": "Ethnobotanical survey of medicinal plants used in management of breast cancers in Qatar.",
        "yil": "2025",
        "kaynakAdi": "PubMed"
    },
    "205": {
        "baslik": "Üreter stentinde yakı otu fitokompleksi",
        "sorun": "Double-J stent takılan 60 hastada stentle ilişkili idrar ve ağrı şikayetleri vardı.",
        "yaklasim": "30 hastaya tamsulosin 0,4 mg, 30 hastaya yakı otu (Epilobium angustifolium) dahil fitokompleks verildi; USSQ skorları 1., 7. ve 21. gün ölçüldü.",
        "sonuc": "Her iki grupta da iyileşme görüldü; idrar semptomlarında 7. ve 21. günde tamsulosin lehine anlamlı fark vardı.",
        "anlatim": "Stent takılan 60 hasta rastgele iki gruba ayrıldı. Bir gruba tamsulosin, diğerine yakı otu içeren fitokompleks verildi. Her iki tedavide de skorlar başlangıca göre iyileşti. İdrar şikayetlerinde tamsulosin grubu anlamlı olarak daha iyi bulundu. Ağrı ve genel sağlık skorlarında anlamlı fark yoktu. Bu metin tıbbi tavsiye değildir.",
        "pubmedId": "42244389",
        "pubmedUrl": "https://pubmed.ncbi.nlm.nih.gov/42244389/",
        "makaleBasligi": "A randomized controlled trial comparing alpha-blocker (tamsulosin) and a phyto-complex (Solidago virga-aurea, Phyllantus niruri, Epilobium angustifolium, Peumus boldus and Ononis spinosa) in the treatment of ureteral stent-related symptoms.",
        "yil": "2026",
        "kaynakAdi": "PubMed"
    },
    "206": {
        "baslik": "Süpürge otu tozuyla aşırı duyarlılık pnömonisi",
        "sorun": "35 yaşındaki süpürge otu (Calluna vulgaris) imalat işçisi kadında üç aydır nefes darlığı, ateş ve öksürük vardı.",
        "yaklasim": "Toraks BT'de buzlu cam opasitesi ve mozaik perfüzyon görüldü; damardan prednizolon başlandı.",
        "sonuc": "Neredeyse tam klinik düzelme sağlandı; mesleki aşırı duyarlılık pnömonisi tanısı kondu.",
        "anlatim": "Süpürge otu üreten kadında nefes darlığı, ateş ve öksürük gelişti. Akciğer görüntülemesinde buzlu cam görünümü vardı. Prednizolon tedavisiyle neredeyse tam düzelme sağlandı. Meslek öyküsünün sorgulanması tanı için önemli vurgulandı. Bu metin tıbbi tavsiye değildir.",
        "pubmedId": "26236625",
        "pubmedUrl": "https://pubmed.ncbi.nlm.nih.gov/26236625/",
        "makaleBasligi": "Hypersensitivity pneumonitis caused by the broom grass (Calluna vulgaris).",
        "yil": "2015",
        "kaynakAdi": "PubMed"
    },
    "208": {
        "baslik": "Venöz bacak ülserinde hint yağı otu yaprağı",
        "sorun": "55 yaşındaki erkekte sol bacakta ağrı, sertlik, renk değişimi, şişlik ve iyileşmeyen venöz ülser vardı.",
        "yaklasim": "Hint yağı otu (Ricinus communis) yapraklarıyla Patradana, macun ve ağızdan Ayurveda ilaçları uygulandı.",
        "sonuc": "10 günde ağrı, şişlik ve sertlikte belirgin azalma; 14 günde yara iyileşmesi bildirildi; 4 ay takipte nüks olmadı.",
        "anlatim": "İyileşmeyen venöz bacak ülseri olan erkeğe hint yağı otu yaprakları dahil Ayurveda bakımı uygulandı. On günde ağrı ve şişlik belirgin azaldı. On dört günde yara iyileşti. Dört aylık takipte ülser tekrarlamadı. Yaşam kalitesi arttığı bildirildi. Tek olgu raporudur. Bu metin tıbbi tavsiye değildir.",
        "pubmedId": "40157249",
        "pubmedUrl": "https://pubmed.ncbi.nlm.nih.gov/40157249/",
        "makaleBasligi": "A non-invasive Ayurveda management of venous leg ulcer- A case report.",
        "yil": "2025",
        "kaynakAdi": "PubMed"
    },
    "210": {
        "baslik": "Sık burkulmada aspir içeren farmakopunktur",
        "sorun": "47 yaşındaki kadın 9 ayda 23 kez diz, başparmak, bilek, ayak bileği ve bel burkulması yaşadı. Akupunktur sonrası bayılma öyküsü nedeniyle iğne tedavisi istemiyordu.",
        "yaklasim": "Scutellaria, Phellodendron ve aspir (Carthamus tinctorius) dahil TA farmakopunktur (ağrı noktalarına bitkisel enjeksiyon) uygulandı.",
        "sonuc": "Tedavi genelde 4 seans içinde tamamlandı; ağrı skoru (VAS) 1'e indi. Hafif ağrıda 1-2 seans sonrası iyileşme bildirildi.",
        "anlatim": "Sık burkulan kadın iğne korkusu nedeniyle alternatif yöntem aradı. Aspir dahil bitkisel ekstrakt enjeksiyonu uygulandı. Tedavi genelde dört seans sürdü. Ağrı skoru 1'e düştü. Hafif burkulmalarda bir-iki seans sonrası rahatlama bildirildi. Tek olgu raporudur. Bu metin tıbbi tavsiye değildir.",
        "pubmedId": "30407331",
        "pubmedUrl": "https://pubmed.ncbi.nlm.nih.gov/30407331/",
        "makaleBasligi": "TA pharmacopuncture as a primary and independent treatment for frequent sprains occurring over 9 months in a patient with needle sickness: Case report.",
        "yil": "2018",
        "kaynakAdi": "PubMed"
    }
}

out_path = r"C:\Users\musta\OneDrive\Desktop\Bitki\data\vaka-rewrite-batch3.json"
with open(out_path, "w", encoding="utf-8") as f:
    json.dump(output, f, ensure_ascii=False, indent=2)

print(f"Written {len(output)} items to {out_path}")
